In [48]:
import numpy as np

# Step 1: Load the .npz file
# Replace 'your_file.npz' with the path to your .npz file
data = np.load('datasets/train/train_feature.npz')
val_data = np.load('datasets/valid/valid_feature.npz')
# Step 2: Check the keys in the .npz file
print("Keys in the .npz file:")
print(data.files)

# Step 3: Access and view the contents of each array
for key in data.files:
    print(f"\nContents of {key}:")
    print(data[key])


Keys in the .npz file:
['features', 'label']

Contents of features:
[[[-0.06862289 -0.02029774  0.06447055 ...  0.06388663 -0.00998752
    0.00310699]
  [ 0.04829922 -0.10981937 -0.01149426 ... -0.04871156  0.26026392
    0.00764406]
  [ 0.01317802  0.17912972  0.05239279 ... -0.10368306 -0.3061711
    0.03993087]
  ...
  [ 0.04056829  0.03725134  0.07697232 ... -0.10133194  0.00529883
    0.01449001]
  [-0.11185187  0.00193434  0.12458888 ...  0.01311917  0.04758739
   -0.02193208]
  [-0.1788078   0.00552609  0.18146187 ... -0.02888818  0.01680396
    0.08289439]]

 [[-0.06862289 -0.02029774  0.06447055 ...  0.06388663 -0.00998752
    0.00310699]
  [ 0.06592898  0.04125806  0.04652221 ... -0.10381559 -0.05420512
   -0.03709979]
  [ 0.01317802  0.17912972  0.05239279 ... -0.10368306 -0.3061711
    0.03993087]
  ...
  [ 0.04056829  0.03725134  0.07697232 ... -0.10133194  0.00529883
    0.01449001]
  [-0.11185187  0.00193434  0.12458888 ...  0.01311917  0.04758739
   -0.02193208]
  [-0.0

In [56]:

features = data['features']
val_features = val_data['features']
print(features.shape)
# Output the shape and some values to verify
summed_features = np.sum(features, axis=2)
summed_val_features = np.sum(val_features, axis=2)

# summed_features_column = summed_features.reshape(-1, 1)  # Reshape to (786, 1)

print("Shape of summed features:", summed_features.shape)
print("First 5 values of the summed features:")
print(summed_features[:5])
print(val_features.shape)

(7080, 13, 768)
Shape of summed features: (7080, 13)
First 5 values of the summed features:
[[-1.0307891   0.3130114  -0.5065322  -1.2744566  -0.9313631  -1.2385731
  -0.9321117   0.46299785 -1.5942653  -0.9313631  -1.2385731  -0.9321117
   0.3889779 ]
 [-1.0307891  -0.9279284  -0.5065322  -1.2744566  -0.9313631  -1.2385731
  -0.9321117   0.91043186 -1.5942653  -0.9313631  -1.2385731  -0.9321117
   0.5479128 ]
 [-1.0307891   0.16563201 -0.5065322  -1.2744566  -0.9313631  -1.2385731
  -0.9321117   0.5615124  -1.5942653  -0.9313631  -1.2385731  -0.9321117
  -0.16408134]
 [-1.0307891   0.16739309 -0.5065322  -1.2744566  -0.9313631  -1.2385731
  -0.9321117  -0.04713106 -1.5942653  -0.9313631  -1.2385731  -0.9321117
   0.15308356]
 [-1.0307891   0.15936828 -0.5065322  -1.2744566  -0.9313631  -1.2385731
  -0.9321117   0.54692376 -1.5942653  -0.9313631  -1.2385731  -0.9321117
   0.5479128 ]]
(489, 13, 768)


In [50]:
import numpy as np
from collections import Counter

# Step 1: Flatten the summed_features array into a 1D array
flattened_features = summed_features.flatten()

# Step 2: Use Counter to count occurrences of each unique value
value_counts = Counter(flattened_features)

# Step 3: Get the 20 most common values
top_7_values = value_counts.most_common(7)

# Step 4: Display the results
print("Top 20 most common feature values and their counts:")
for value, count in top_7_values:
    print(f"Value: {value}, Count: {count}")


Top 20 most common feature values and their counts:
Value: -0.9313631057739258, Count: 14160
Value: -1.2385730743408203, Count: 14160
Value: -0.9321116805076599, Count: 14160
Value: -1.0307891368865967, Count: 7080
Value: -0.5065321922302246, Count: 7080
Value: -1.2744566202163696, Count: 7080
Value: -1.594265341758728, Count: 7080


In [57]:
import numpy as np

# Step 1: Flatten the summed_features array (7080, 13) to a 1D array for easy comparison
# flattened_features = summed_features.flatten()

# Step 2: Identify the common values (let's assume they are in a list called `common_values`)
common_values = [value for value, count in top_7_values]  # top_20_values contains the most common values

# Step 3: Reshape the flattened_features back into (7080, 13)
reshaped_features = summed_features

# Step 4: Filter out columns with the common values across all entries
filtered_matrix = np.zeros((7080, 0))  # Start with an empty matrix for the filtered data

for i in range(13):
    # Get the ith column across all entries
    column_data = reshaped_features[:, i]
    
    # Check if the column contains one of the common values
    if not np.any(np.isin(column_data, common_values)):
        # If the column doesn't contain any common values, keep it
        filtered_matrix = np.column_stack((filtered_matrix, column_data))

# Step 5: The resulting matrix should have fewer columns
print("Shape of the filtered matrix:", filtered_matrix.shape)
print(filtered_matrix[:5])

# Expected shape after removing 10 features: (7080, 3)


Shape of the filtered matrix: (7080, 3)
[[ 0.31301141  0.46299785  0.38897789]
 [-0.92792839  0.91043186  0.54791278]
 [ 0.16563201  0.56151241 -0.16408134]
 [ 0.16739309 -0.04713106  0.15308356]
 [ 0.15936828  0.54692376  0.54791278]]


In [58]:
filtered_val_matrix = np.zeros((489,0))
reshaped_val_features = summed_val_features
for i in range(13):
    # Get the ith column across all entries
    column_data = reshaped_val_features[:, i]
    
    # Check if the column contains one of the common values
    if not np.any(np.isin(column_data, common_values)):
        # If the column doesn't contain any common values, keep it
        filtered_val_matrix = np.column_stack((filtered_val_matrix, column_data))
print(filtered_val_matrix[:5])

[[-0.02527267  0.31488031 -0.03420395]
 [-0.19246811  0.05495048  0.17093211]
 [-1.7425065   0.61778539  0.19043392]
 [ 0.88477898 -0.97780907  0.38897789]
 [-0.44203496  0.02192831  0.40169394]]


In [61]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding
from sklearn.preprocessing import LabelEncoder

# Assuming filtered_matrix is a numpy array (7080, 13)
# and top_3_feature_indices is a list containing the column indices of the 3 most common features
top_3_feature_indices = [0, 1, 2]  # Replace with actual indices of the 3 common features

# Step 1: Extract the 3 most common features from the matrix
filtered_matrix_top3 = filtered_matrix[:, top_3_feature_indices]
filtered_val_matrix_top3 = filtered_val_matrix[:, top_3_feature_indices]

# Convert this to a DataFrame for easier manipulation
df_top3 = pd.DataFrame(filtered_matrix_top3, columns=['Feature_1', 'Feature_2', 'Feature_3'])
df_val_top3 = pd.DataFrame(filtered_val_matrix_top3, columns=['Feature_1', 'Feature_2', 'Feature_3'])
print(df_top3.head())  # Preview the top 3 features
# Assuming your labels are in a column or a separate array (y_labels)
y_labels = data['label']  # Replace with actual label column

# Step 3: Encode the labels (if necessary)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y_labels)
y_val_encoded = label_encoder.fit_transform(val_data['label'])
# print(y_encoded)
# Step 4: Split into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(df_top3, y_encoded, test_size=0.2, random_state=42)

# print("Training set size:", X_train.shape)
# print("Test set size:", X_test.shape)


   Feature_1  Feature_2  Feature_3
0   0.313011   0.462998   0.388978
1  -0.927928   0.910432   0.547913
2   0.165632   0.561512  -0.164081
3   0.167393  -0.047131   0.153084
4   0.159368   0.546924   0.547913


In [108]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM,Dropout,Conv1D,SimpleRNN
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score


# Assuming filtered_matrix is of shape (7080, 3) from the previous steps
from tensorflow.keras.preprocessing.text import Tokenizer
df_top3_str = df_top3.apply(lambda row: ' '.join(map(str, row)), axis=1)
df_val_top3_str = df_val_top3.apply(lambda row: ' '.join(map(str, row)), axis=1)

# Step 1: Tokenizer for numerical features
# Since the features are integers, we first need to convert them to strings for Tokenizer to work.
# df_top3_str = df_top3.astype(str)

# Initialize the tokenizer
tokenizer = Tokenizer()

# Fit the tokenizer on the features
tokenizer.fit_on_texts(df_top3_str.values)

# Step 2: Convert the integer sequences to tokenized sequences
X_tokenized = tokenizer.texts_to_sequences(df_top3_str.values)
X_val_tokenized = tokenizer.texts_to_sequences(df_val_top3_str.values)
max_len = max(len(x) for x in X_tokenized)
# Since tokenizer output is a list of lists, convert it back to a numpy array
X_padded = pad_sequences(X_tokenized, padding='post',maxlen = max_len)  # Use padding if necessary
X_val_padded = pad_sequences(X_val_tokenized, padding='post',maxlen = max_len)  # Use padding if necessary

print("Tokenized sequences shape:", X_padded.shape)
X_train, X_test, y_train, y_test = train_test_split(X_padded, y_encoded, test_size=0.2, random_state=42)

print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)
print(y_train.shape)
# Step 5: Define the neural network model
model = Sequential()

# Embedding layer with pre-trained embeddings (trainable=False)
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=50, input_length=max_len, trainable=False))

# Convolutional layer with fewer filters
model.add(Conv1D(filters=48, kernel_size=1, activation='relu'))
# model.add(MaxPooling1D(pool_size=2))

# LSTM layer with fewer units
model.add((LSTM(20, return_sequences=False)))

# Dense layers with Dropout
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=20, batch_size=16, verbose=1)
# Step 8: Evaluate the model
y_pred = (model.predict(X_val_padded) > 0.5).astype(int)

# Evaluate the model
accuracy = accuracy_score(y_val_encoded, y_pred)
print(f"Neural Network Test Accuracy: {accuracy * 100:.2f}%")
model.summary()
# Step 9: Make predictions
# Threshold for binary classification


Tokenized sequences shape: (7080, 6)
Training set size: (5664, 6)
Test set size: (1416, 6)
(5664,)
Epoch 1/20


/home/baftol/.local/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


354/354 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5127 - loss: 0.6929
Epoch 2/20
354/354 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7920 - loss: 0.4243
Epoch 3/20
354/354 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9464 - loss: 0.1376
Epoch 4/20
354/354 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9582 - loss: 0.0996
Epoch 5/20
354/354 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9667 - loss: 0.0797
Epoch 6/20
354/354 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9651 - loss: 0.0783
Epoch 7/20
354/354 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9685 - loss: 0.0714
Epoch 8/20
354/354 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9719 - loss: 0.0665
Epoch 9/20
354/354 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9718 - loss: 0.0633
Epoch 10/20
354/354 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9700 - loss: 0.0662
Epoch 11/20
354/354 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9652 - loss: 0.0697
Epoch 12/20
354/354 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy

Model: "sequential_61"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_60 (Embedding)        │ (16, 6, 50)            │        10,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_56 (Conv1D)              │ (16, 6, 48)            │         2,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_52 (LSTM)                  │ (16, 20)               │         5,520 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_125 (Dense)               │ (16, 64)               │         1,344 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_60 (Dropout)            │ (16, 64)               │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_126 (Dense)               │ (16, 1)                │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 38,633 (150.91 KB)

 Trainable params: 9,377 (36.63 KB)

 Non-trainable params: 10,500 (41.02 KB)

 Optimizer params: 18,756 (73.27 KB)