In [4]:
import numpy as np

# Step 1: Load the .npz file
# Replace 'your_file.npz' with the path to your .npz file
data = np.load('datasets/train/train_feature.npz')

# Step 2: Check the keys in the .npz file
print("Keys in the .npz file:")
print(data.files)

# Step 3: Access and view the contents of each array
for key in data.files:
    print(f"\nContents of {key}:")
    print(data[key])


Keys in the .npz file:
['features', 'label']

Contents of features:
[[[-0.06862289 -0.02029774  0.06447055 ...  0.06388663 -0.00998752
    0.00310699]
  [ 0.04829922 -0.10981937 -0.01149426 ... -0.04871156  0.26026392
    0.00764406]
  [ 0.01317802  0.17912972  0.05239279 ... -0.10368306 -0.3061711
    0.03993087]
  ...
  [ 0.04056829  0.03725134  0.07697232 ... -0.10133194  0.00529883
    0.01449001]
  [-0.11185187  0.00193434  0.12458888 ...  0.01311917  0.04758739
   -0.02193208]
  [-0.1788078   0.00552609  0.18146187 ... -0.02888818  0.01680396
    0.08289439]]

 [[-0.06862289 -0.02029774  0.06447055 ...  0.06388663 -0.00998752
    0.00310699]
  [ 0.06592898  0.04125806  0.04652221 ... -0.10381559 -0.05420512
   -0.03709979]
  [ 0.01317802  0.17912972  0.05239279 ... -0.10368306 -0.3061711
    0.03993087]
  ...
  [ 0.04056829  0.03725134  0.07697232 ... -0.10133194  0.00529883
    0.01449001]
  [-0.11185187  0.00193434  0.12458888 ...  0.01311917  0.04758739
   -0.02193208]
  [-0.0

In [12]:

features = data['features']
print(features.shape)
# Output the shape and some values to verify
summed_features = np.sum(features, axis=2)
# summed_features_column = summed_features.reshape(-1, 1)  # Reshape to (786, 1)

print("Shape of summed features:", summed_features.shape)
print("First 5 values of the summed features:")
print(summed_features[:5])

(7080, 13, 768)
Shape of summed features: (7080, 13)
First 5 values of the summed features:
[[-1.0307891   0.3130114  -0.5065322  -1.2744566  -0.9313631  -1.2385731
  -0.9321117   0.46299785 -1.5942653  -0.9313631  -1.2385731  -0.9321117
   0.3889779 ]
 [-1.0307891  -0.9279284  -0.5065322  -1.2744566  -0.9313631  -1.2385731
  -0.9321117   0.91043186 -1.5942653  -0.9313631  -1.2385731  -0.9321117
   0.5479128 ]
 [-1.0307891   0.16563201 -0.5065322  -1.2744566  -0.9313631  -1.2385731
  -0.9321117   0.5615124  -1.5942653  -0.9313631  -1.2385731  -0.9321117
  -0.16408134]
 [-1.0307891   0.16739309 -0.5065322  -1.2744566  -0.9313631  -1.2385731
  -0.9321117  -0.04713106 -1.5942653  -0.9313631  -1.2385731  -0.9321117
   0.15308356]
 [-1.0307891   0.15936828 -0.5065322  -1.2744566  -0.9313631  -1.2385731
  -0.9321117   0.54692376 -1.5942653  -0.9313631  -1.2385731  -0.9321117
   0.5479128 ]]


In [14]:
import numpy as np
from collections import Counter

# Step 1: Flatten the summed_features array into a 1D array
flattened_features = summed_features.flatten()

# Step 2: Use Counter to count occurrences of each unique value
value_counts = Counter(flattened_features)

# Step 3: Get the 20 most common values
top_7_values = value_counts.most_common(7)

# Step 4: Display the results
print("Top 20 most common feature values and their counts:")
for value, count in top_7_values:
    print(f"Value: {value}, Count: {count}")


Top 20 most common feature values and their counts:
Value: -0.9313631057739258, Count: 14160
Value: -1.2385730743408203, Count: 14160
Value: -0.9321116805076599, Count: 14160
Value: -1.0307891368865967, Count: 7080
Value: -0.5065321922302246, Count: 7080
Value: -1.2744566202163696, Count: 7080
Value: -1.594265341758728, Count: 7080


In [17]:
import numpy as np

# Step 1: Flatten the summed_features array (7080, 13) to a 1D array for easy comparison
# flattened_features = summed_features.flatten()

# Step 2: Identify the common values (let's assume they are in a list called `common_values`)
common_values = [value for value, count in top_7_values]  # top_20_values contains the most common values

# Step 3: Reshape the flattened_features back into (7080, 13)
reshaped_features = summed_features

# Step 4: Filter out columns with the common values across all entries
filtered_matrix = np.zeros((7080, 0))  # Start with an empty matrix for the filtered data

for i in range(13):
    # Get the ith column across all entries
    column_data = reshaped_features[:, i]
    
    # Check if the column contains one of the common values
    if not np.any(np.isin(column_data, common_values)):
        # If the column doesn't contain any common values, keep it
        filtered_matrix = np.column_stack((filtered_matrix, column_data))

# Step 5: The resulting matrix should have fewer columns
print("Shape of the filtered matrix:", filtered_matrix.shape)
print(filtered_matrix[:5])
# Expected shape after removing 10 features: (7080, 3)


Shape of the filtered matrix: (7080, 3)
[[ 0.31301141  0.46299785  0.38897789]
 [-0.92792839  0.91043186  0.54791278]
 [ 0.16563201  0.56151241 -0.16408134]
 [ 0.16739309 -0.04713106  0.15308356]
 [ 0.15936828  0.54692376  0.54791278]]


In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding
from sklearn.preprocessing import LabelEncoder

# Assuming filtered_matrix is a numpy array (7080, 13)
# and top_3_feature_indices is a list containing the column indices of the 3 most common features
top_3_feature_indices = [0, 1, 2]  # Replace with actual indices of the 3 common features

# Step 1: Extract the 3 most common features from the matrix
filtered_matrix_top3 = filtered_matrix[:, top_3_feature_indices]

# Convert this to a DataFrame for easier manipulation
df_top3 = pd.DataFrame(filtered_matrix_top3, columns=['Feature_1', 'Feature_2', 'Feature_3'])
print(df_top3.head())  # Preview the top 3 features
# Assuming your labels are in a column or a separate array (y_labels)
y_labels = data['label']  # Replace with actual label column

# Step 3: Encode the labels (if necessary)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y_labels)
# print(y_encoded)
# Step 4: Split into training and testing sets


             Feature_1             Feature_2             Feature_3
0  0.31301140785217285    0.4629978537559509   0.38897788524627686
1  -0.9279283881187439    0.9104318618774414    0.5479127764701843
2  0.16563200950622559    0.5615124106407166  -0.16408133506774902
3  0.16739308834075928  -0.04713106155395508   0.15308356285095215
4  0.15936827659606934    0.5469237565994263    0.5479127764701843
[0 0 0 ... 1 0 0]
Training set size: (5664, 3)
Test set size: (1416, 3)


In [43]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM,Dropout,Conv1D,SimpleRNN
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score


# Assuming filtered_matrix is of shape (7080, 3) from the previous steps
from tensorflow.keras.preprocessing.text import Tokenizer
df_top3_str = df_top3.apply(lambda row: ' '.join(map(str, row)), axis=1)

# Step 1: Tokenizer for numerical features
# Since the features are integers, we first need to convert them to strings for Tokenizer to work.
# df_top3_str = df_top3.astype(str)

# Initialize the tokenizer
tokenizer = Tokenizer()

# Fit the tokenizer on the features
tokenizer.fit_on_texts(df_top3_str.values)

# Step 2: Convert the integer sequences to tokenized sequences
X_tokenized = tokenizer.texts_to_sequences(df_top3_str.values)
max_len = max(len(x) for x in X_tokenized)
# Since tokenizer output is a list of lists, convert it back to a numpy array
X_padded = pad_sequences(X_tokenized, padding='post',maxlen = max_len)  # Use padding if necessary

print("Tokenized sequences shape:", X_padded.shape)
X_train, X_test, y_train, y_test = train_test_split(X_padded, y_encoded, test_size=0.8, random_state=42)

print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)
print(y_train.shape)
# Step 5: Define the neural network model
model = Sequential()

# Embedding layer with pre-trained embeddings (trainable=False)
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=50, input_length=max_len, trainable=False))

# Convolutional layer with fewer filters
model.add(Conv1D(filters=48, kernel_size=1, activation='relu'))
# model.add(MaxPooling1D(pool_size=2))

# LSTM layer with fewer units
model.add((LSTM(20, return_sequences=False)))

# Dense layers with Dropout
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=30, batch_size=64, verbose=1)
# Step 8: Evaluate the model
y_pred = (model.predict(X_test) > 0.5).astype(int)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Neural Network Test Accuracy: {accuracy * 100:.2f}%")
model.summary()
# Step 9: Make predictions
# Threshold for binary classification


Tokenized sequences shape: (7080, 6)
Training set size: (1416, 6)
Test set size: (5664, 6)
(1416,)
Epoch 1/30


/home/baftol/.local/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4914 - loss: 0.6933
Epoch 2/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4995 - loss: 0.6931 
Epoch 3/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5034 - loss: 0.6931 
Epoch 4/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4934 - loss: 0.6930 
Epoch 5/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5364 - loss: 0.6916 
Epoch 6/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5963 - loss: 0.6898 
Epoch 7/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6128 - loss: 0.6841 
Epoch 8/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6450 - loss: 0.6654 
Epoch 9/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5978 
Epoch 10/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7522 - loss: 0.5008 
Epoch 11/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7989 - loss: 0.4241 
Epoch 12/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8292 - los

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)        │ (None, 6, 50)          │        10,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_9 (Conv1D)               │ (None, 6, 48)          │         2,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ (None, 20)             │         5,520 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_31 (Dense)                │ (None, 64)             │         1,344 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_13 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 38,633 (150.91 KB)

 Trainable params: 9,377 (36.63 KB)

 Non-trainable params: 10,500 (41.02 KB)

 Optimizer params: 18,756 (73.27 KB)